### PR TITLE
Fix base64 image upload

### LINKED ISSUE #412: Avoid save base64 images on MongoDb
When a user uploads an image while offline, it is stored on the device as a base64 image. When the board is stored or updated in the database, the image is also saved as base64. This issue increases the database size and fills up the user's device memory.

Fix:
We must implement a functionality to store the image as a blob in the Cboard blob storage before upserting the board into the database.

### PR DESCRIPTION
**Pull request by magush27**
Handling of offline board updates with base64 images, enhancing error reporting,

**Offline Board Update & Image Processing Enhancements:**

* Added detection and processing of base64 images in `updateBoard` for offline syncs, utilizing `processBase64Images` and `hasBase64Images` from `imageProcessor`. The system now processes these images, uploads them to blob storage, and updates the board tiles accordingly. Detailed logging and error handling/reporting are included to inform the client of any image processing issues. (`api/controllers/board.js`)
* The board update response now includes an `imageProcessing` field if any image processing errors occurred, providing clear feedback to clients about which images may not have uploaded successfully. (`api/controllers/board.js`)

**Blob Storage Helper Update:**

* Added explicit null assignments for `contentEncoding`, `contentLanguage`, and `contentMD5` in the blob upload helper to ensure consistent blob metadata when uploading images. (`api/helpers/blob.js`)

Closes #412

### CODE REVIEW

File: api/helpers/imageProcessor.js [hunk 1]
```diff
@@ -0,0 +1,409 @@
...
+    const batchResults = await Promise.allSettled(batchPromises);
+    logBatchResults(i, batchResults);
+  }
+
+  // Reconstruct array in original order
+  const processedTiles = tiles.map((tile, index) => {
+    const tileId = tile.id || `tile_${index}`;
+    const result = resultMap.get(tileId);
+    return result || tile;
+  });
```
Comment (RodriSanchez1) [inline api/helpers/imageProcessor.js:120]: I sugggest a refactor that improves performance and maintainability while preserving the existing batching logic and error handling. The function now eliminates redundant data structures and relies on a single tileMap as the source of truth, which makes the data flow simpler and easier to reason about. Instead of duplicating tile objects, it uses an ID array to manage the processing queue

Also avoids adding the fields `error, status and originalIndex` to the existing Tiles

Let me know your thoughts please

```suggestion

async function processWithMap(tiles, containerName = BLOB_CONTAINER_NAME) {
  const tileMap = new Map();
  const toProcessIds = [];
  const errorMap = new Map();
  let successCount = 0;
  let failureCount = 0;

  tiles.forEach((tile, index) => {
    const tileId = tile.id || `tile_${index}`;
    tileMap.set(tileId, { ...tile });

    if (tile.image && isBase64Image(tile.image)) {
      toProcessIds.push(tileId);
    }
  });
  
  for (let i = 0; i < toProcessIds.length; i += CONFIG.BATCH_SIZE) {
    const batchIds = toProcessIds.slice(i, i + CONFIG.BATCH_SIZE);
    
    const batchPromises = batchIds.map(async (tileId) => {
      const tile = tileMap.get(tileId);
      try {
        const blobUrl = await convertBase64ToBlob(tile.image, containerName, {
          enableRetries: true,
          maxRetries: CONFIG.MAX_RETRIES,
          enableCache: CONFIG.ENABLE_CACHE,
          tileId,
          tile: tile
        });
        
        const tileData = tileMap.get(tileId);
        tileMap.set(tileId, {
          ...tileData,
          image: blobUrl
        });
        
        successCount++;
        return { success: true, tileId };
        
      } catch (error) {
        failureCount++;
        const errorInfo = createErrorInfo(tile, error);
        errorMap.set(tileId, errorInfo);
      
        const errorHandledTile = handleImageError(tile, error);
        if (errorHandledTile.image !== tile.image) {
          const tileData = tileMap.get(tileId);
          tileMap.set(tileId, {
            ...tileData,
            image: errorHandledTile.image
          });
        }
        
        return { success: false, tileId, error: errorInfo };
      }
    });
    
    const batchResults = await Promise.allSettled(batchPromises);
    logBatchResults(i, batchResults);
  }

  const processedTiles = tiles.map((tile, index) => {
    const tileId = tile.id || `tile_${index}`;
    const result = tileMap.get(tileId);
    return result || tile;
  });
```

File: api/helpers/imageProcessor.js [hunk 2]
```diff
@@ -0,0 +1,409 @@
...
+ * @param {string} base64String - The base64 image string
+ * @param {string} containerName - Azure container name
+ * @param {Object} options - Configuration options
+ * @param {boolean} options.enableRetries - Enable retry logic (default: false)
+ * @param {number} options.maxRetries - Maximum retry attempts (default: 3)
+ * @param {boolean} options.enableCache - Enable image caching (default: false)
+ * @param {string} options.tileId - Tile ID for logging (default: 'unknown')
+ * @param {Object} options.tile - Tile object containing label and other data (optional)
+ * @returns {Promise<string>} The blob CDN URL
+ */
```
Comment (RodriSanchez1) [inline api/helpers/imageProcessor.js:148]: If you will add the function definition, please be consiste with the other functions, at least the important ones as `processWithMap()` . I suggest to add the definition on the other functions

File: api/helpers/imageProcessor.js [hunk 3]
```diff
@@ -0,0 +1,409 @@
...
+  INVALID_BASE64: 'Invalid base64 format',
+  AZURE_UPLOAD_FAILED: 'Azure blob upload failed',
+  AZURE_RATE_LIMIT: 'Azure rate limit exceeded',
+  NETWORK_TIMEOUT: 'Network timeout',
+  INSUFFICIENT_STORAGE: 'Storage quota exceeded',
+  INVALID_IMAGE_FORMAT: 'Unsupported image format'
+};
+
+// Global image cache - maps content hash to blob URL
+const imageCache = new Map();
```
Comment (RodriSanchez1) [inline api/helpers/imageProcessor.js:25]: Please remove this `imageCache` map. It can produce a memory leak because it can grow indefinitely. It never gets cleaned.

Also I think that not to many images are duplicated, so we will be good if each blob is processed

File: api/helpers/imageProcessor.js [hunk 4]
```diff
@@ -0,0 +1,409 @@
...
+  } = options;
+
+  if (enableCache) {
+    const cacheKey = createImageHash(base64String);
+    if (imageCache.has(cacheKey)) {
+      incrementCacheStats('hits');
+      return imageCache.get(cacheKey);
+    }
+    incrementCacheStats('misses');
+  }
```
Comment (RodriSanchez1) [inline api/helpers/imageProcessor.js:165]: We can avoid the image cache. I left a comment above

File: api/helpers/imageProcessor.js [hunk 5]
```diff
@@ -0,0 +1,409 @@
...
+    
+    // Cache successful result
+    if (enableCache) {
+      const cacheKey = createImageHash(base64String);
+      imageCache.set(cacheKey, blobUrl);
+    }
+    
+    return blobUrl;
+  }
+}
```
Comment (RodriSanchez1) [inline api/helpers/imageProcessor.js:231]: consider improving this code block to avoid code duplication

File: api/helpers/imageProcessor.js [hunk 6]
```diff
@@ -0,0 +1,409 @@
...
+
+// Handle image processing error based on error type
+function handleImageError(tile, error) {
+  const errorType = classifyError(error);
+  
+  switch (errorType) {
+    case ErrorTypes.INVALID_BASE64:
+    case ErrorTypes.INVALID_IMAGE_FORMAT:
+      // Remove invalid image completely
+      return { ...tile, image: null, hasImageError: true, errorType };
```
Comment (RodriSanchez1) [inline api/helpers/imageProcessor.js:279]: Avoid adding extra fields to the tile like `hasImageError or errorType`

File: api/helpers/imageProcessor.js [hunk 7]
```diff
@@ -0,0 +1,409 @@
...
+}
+
+/**
+ * Create unique filename from tile data
+ * @param {Object} tile - Tile object
+ * @param {string} extension - File extension
+ * @param {string} fallbackId - Fallback ID if no tile data available
+ * @returns {string} Sanitized filename
+ */
+function createUniqueFilename(tile, extension, fallbackId = 'unknown') {
```
Comment (RodriSanchez1) [inline api/helpers/imageProcessor.js:358]: I think this function is defined in `media.js`, if that is correct please import it on this file. In that way we avoid code duplication and we are sure that all the image names follows the same pattern

File: api/helpers/imageProcessor.js [hunk 8]
```diff
@@ -0,0 +1,409 @@
...
+  cacheStats[type]++;
+}
+
+function getCacheStats() {
+  return { ...cacheStats };
+}
+
+function resetCacheStats() {
+  cacheStats = { hits: 0, misses: 0 };
+}
```
Comment (RodriSanchez1) [inline api/helpers/imageProcessor.js:349]: Remove this functions as are part of the cacheImage logic

**Review by RodriSanchez1 — CHANGES_REQUESTED** [review]
Hello Agus! That's was an awesome job! I left some comments! Le me know if you have any doubt

File: api/helpers/blob.js [hunk 9]
```diff
@@ -36,6 +36,9 @@ async function createBlockBlobFromText(
     const cacheMaxAgeInSeconds = 31536000;
     options.contentSettings = {
       contentType: mimetype,
+      contentEncoding: null,
+      contentLanguage: null,
+      contentMD5: null,
```
[the remark this answers is not in the document]
Comment (magush27) [reply api/helpers/blob.js:41]: I added it to prevent unpredictable behaviour. Azure uses it's defaults but it can make some assumptions on the files we are trying to upload. So I added `contentEncoding: null` to ensure there is no compression encoding applied by default that can corrupt the images like gzip. I added `contentLanguage: null` to prevent automatic language detection that can interfere with the file being uploaded. I added `contentMD5: null` to disable automatic MD5 checksum validation that can cause upload failures to Azure if the computed hash doesn't match. 
This can be omitted, I was just being explicit about what we don't want rather than relying on potentially changing defaults

File: api/helpers/imageProcessor.js
[the remark this answers is not in the document]
Comment (magush27) [reply api/helpers/imageProcessor.js:1]: I removed all the comments in a commit

File: api/controllers/board.js [hunk 10]
```diff
@@ -140,8 +142,62 @@ async function updateBoard(req, res) {
...
+        console.error('Offline sync image processing failed:', {
+          boardId: id,
+          error: imageError.message,
+          tilesCount: updateData.tiles.length
+        });
+        
+        updateData._imageProcessingErrors = {
+          hasErrors: true,
+          errorMessage: 'Image processing failed - tiles kept as base64'
+        };
```
[the remark this answers is not in the document]
Comment (magush27) [reply api/controllers/board.js:192]: Great! I added it in a commit

File: api/helpers/imageProcessor.js (hunk 1 above)
Comment (magush27) [reply api/helpers/imageProcessor.js]: I've commited your changes because they are great!

File: api/helpers/imageProcessor.js (hunk 2 above)
Comment (magush27) [reply api/helpers/imageProcessor.js:129]: I added it in a commit

File: api/helpers/imageProcessor.js (hunk 7 above)
Comment (magush27) [reply api/helpers/imageProcessor.js:339]: I looked up `media.js` and it uses `uploadedFile.originalname` to set the name, so it doesn't have a way to do it.. maybe in the frontend there is something

File: api/helpers/imageProcessor.js (hunk 8 above)
Comment (magush27) [reply api/helpers/imageProcessor.js:330]: Deleted it in a commit mentioned previously

File: api/helpers/imageProcessor.js (hunk 6 above)
Comment (magush27) [reply api/helpers/imageProcessor.js:260]: Solved this in a commit

File: api/helpers/imageProcessor.js (hunk 7 above)
Comment (magush27) [reply api/helpers/imageProcessor.js:279]: no, I need to check that. I will do it now
